baseURL: "https://www.example.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "صلحا"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "صلحا"
  description: "محلی برای اطلاع پیدا کردن از زندگی صلحا"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    github: "https://github.com/solaha-net/website"
    # dribbble: "#"
    # instagram: "#"
    # facebook: "#"
    # twitter: "#"

  location:
    - "قطعه شهدا - بهشت زهرا سلام الله علیها"

  contact:
    - 

  copyright: "© 2022 صلحا All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 5

  # buttons:
  #   - name: "Book a call"
  #     url: "/#"
  #     weight: 5
  #     pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/"
      weight: 1

    - name: "Blog"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"

build:
  writeStats: false
